[package]
name = "edu-subxt"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
subxt = { version = "0.27.1", features = ["substrate-compat", "jsonrpsee-ws"] }
parity-scale-codec = { version = "3.4.0", features = ["derive"] }
async-trait = "*"